config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  # validates_presence_of :comment
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_post, only: %i[show edit update destroy]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show; end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment_settings">
   <%if user_signed_in?%>
   <%if current_user.id == comment.user_id %>
   <%= link_to "Edit comment", edit_post_comment_path(@post, comment) %>
   <%= link_to "Delete comment", [comment.post, comment], method: :delete,  data: { confirm: 'Are you sure?'}%>
   <%end%>
   <%end%>
</div>
<div class="comment">
   <p>On <%= comment.created_at.strftime("%Y-%m-%d")%> <%=comment.user.email%> wrote:</p>
   <p><%= comment.comment%></p>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @post.comments.build] do |f| %>
    <%= f.input :comment, placeholder: 'Write message',input_html: { class: 'form-control' } %>
    <%= f.submit class: 'btn btn-primary' %> 
<% end %>

app/views/comments/edit.html.erb
<div class="post_form">
   <h1>Edit form</h1>
   <%= simple_form_for [@post, @comment] do |f| %>
   <%= f.input :comment, input_html: { class: 'form-control' } %>
   <%= f.submit %>
   <% end %>
   <%= link_to "Cancel", post_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Forum</title>
      <%= csrf_meta_tags %>
      <link href="https://fonts.googleapis.com/css?family=Droid+Sans|Muli" rel="stylesheet">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>
   <body>
      <div class="navbar-wrapper">
         <div class="container-fluid">
            <nav class="navbar navbar-fixed-top">
               <div class="container">
                  <div class="navbar-header">
                     <%= link_to "Lorem ipsum forum", root_path,:class => "navbar-brand" %> 
                  </div>
                  <div id="navbar" class="navbar-collapse collapse">
                     <ul class="nav navbar-nav pull-right">
                        <% if user_signed_in? %>
                        <li>
                           <%= link_to "New post", new_post_path %>
                        </li>
                        <li >
                           <%= link_to "Delete my account",
                              registration_path(current_user),
                              data: { confirm: "Are you sure?" },
                              method: :delete %> 
                        </li>
                        <li >
                           <%= link_to "Log out", destroy_user_session_path, method: :delete %>     
                        </li>
                        <% else %>
                        <li >
                           <%= link_to "Sign up ", new_user_registration_path %>
                        </li>
                        <li>
                           <%= link_to "Sign in ", new_user_session_path %> 
                        </li>
                        <% end %> 
                     </ul>
                  </div>
               </div>
            </nav>
         </div>
      </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="wrapper">
         <%= yield %>
      </div>
   </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
<p>Forum topic</p>
<p><%= f.input :title, label: false%></p>
<p>Message</p>
<%= f.input :content, label: false, input_html: { class: 'form-control' }%>
<%= f.submit "#{@post.new_record? ? 'Create' : 'Edit'}", class: 'btn btn-primary'%>
<% end %>

app/views/posts/edit.html.erb
<div class="form">
   <div class="post_form">
      <h1>Edit form</h1>
      <%= render 'form' %>
      <%= link_to "Cancel", post_path %>
   </div>
</div>

app/views/posts/index.html.erb
<div class="forum_news">
   <div id="posts">
      <% @posts.each do |post| %>		 
      <div class="post">
         <%= link_to post.title, post, class: 'title'%> 
         <p class="date">Published by <%= post.user.email %>
            <%= time_ago_in_words(post.updated_at) + " ago"%>
         </p>
      </div>
      <%end%>
   </div>
</div>

app/views/posts/new.html.erb
<div class="post_form">
   <h1>New Post</h1>
   <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
   <div class="post_settings">
      <%if user_signed_in?%>
      <%if current_user.id == @post.user_id   %>
      <%= link_to "Edit", edit_post_path(@post) %> 
      <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%end%>
      <%end%>
      <%= link_to "Home Page", root_path %>
   </div>
   <h1><%=@post.title%></h1>
   <p><%=@post.content%></p>
   <div id="comments">
      <%if user_signed_in?%>
      <h2> Comments </h2>
      <%= render @post.comments %>
      <h3>Reply to thread</h3>
      <%= render 'comments/form' %>
   </div>
</div>
<%else%>
<h2> Comments </h2>
<%= render @post.comments %>
<p style="text-align: center ;
   font-size: 12px;">To write comments <%= link_to "login", new_user_session_path%></p>
</div>
<%end%>